testname: Thesis Questionnaire
testId: thesis_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to WebMUSHRA! 
               <br/>
               <br/>
               This study, "A Comparative Evaluation of Tonal Replication Techniques for Music Composition and Sound Design Through Tonal Synthesis" aims to analyze different methods of audio synthesis and replication of different machine learning models and how they compare in their accuracy + efficiency in replicating instrumental tones.
    - type: consent
      id: consent_page
      name: Consent
      mustConsent: true
      content: <h1>Welcome to Our Audio Quality Study!</h1> <p>Thank you for taking the time to participate in this research. Before proceeding, please read the information below about the study and your rights as a participant:</p> <h2>Purpose of the Study</h2> <p>This study aims to evaluate the quality of audio samples generated by machine learning models. Your valuable feedback will help us improve audio synthesis technology.</p> <h2>What You Will Do</h2> <p>You will be asked to listen to short audio samples and provide subjective feedback on their quality. The process should take approximately <strong>[insert estimated time]</strong>.</p> <h2>Voluntary Participation</h2> <p>Your participation in this study is entirely voluntary. You may choose to stop participating at any time without any penalty.</p> <h2>Minimal Risk</h2> <p>This study involves minimal risk. It requires only your time and subjective input. No sensitive or personally identifiable information will be collected, and there are no physical, emotional, or psychological risks involved.</p> <h2>Privacy and Confidentiality</h2> <p>Your responses will remain anonymous and will be used solely for research purposes. No identifying information will be collected or shared.</p> <h2>Consent to Participate</h2> <p>By clicking "Start" or selecting "Yes, I agree" below, you confirm that:</p> <ul> <li>You have read and understood the information provided above.</li> <li>You are voluntarily agreeing to participate in this study.</li> <li>You understand that you can withdraw at any time.</li> </ul>
    - type: mushra
      id: training_page
      name: MUSHRA
      content: This training shows how to use our user interface. Please perform the underlined instructions to proceed with the training session. Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/mono_ref.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/mono_c1.wav
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav
    - 
          - random
          - type: mushra
            id: trial_brass
            name: MUSHRA Test
            content: This page shows a trial according to ITU-R Recommendation BS.1534. (Brass)
            enableLooping: true
            switchBack: true
            reference: configs/resources/audio/brass_acoustic_006-032-075/original.wav
            createAnchor35: false
            createAnchor70: true
            stimuli:
                ddsp: configs/resources/audio/brass_acoustic_006-032-075/ddsp.wav
                dwts: configs/resources/audio/brass_acoustic_006-032-075/dwts.wav
                nic: configs/resources/audio/brass_acoustic_006-032-075/nic.wav
          - type: mushra
            id: trial_flute
            name: MUSHRA Test
            content: This page shows a trial according to ITU-R Recommendation BS.1534. (Flute)
            enableLooping: true
            switchBack: true
            reference: configs/resources/audio/flute_acoustic_002-078-025/original.wav
            createAnchor35: false
            createAnchor70: true
            stimuli:
                ddsp: configs/resources/audio/flute_acoustic_002-078-025/ddsp.wav
                dwts: configs/resources/audio/flute_acoustic_002-078-025/dwts.wav
                nic: configs/resources/audio/flute_acoustic_002-078-025/nic.wav
          - type: mushra
            id: trial_guitar_lower
            name: MUSHRA Test
            content: This page shows a trial according to ITU-R Recommendation BS.1534. (Guitar_Lower)
            enableLooping: true
            switchBack: true
            reference: configs/resources/audio/guitar_acoustic_030-062-050_lower/original.wav
            createAnchor35: false
            createAnchor70: true
            stimuli:
                ddsp: configs/resources/audio/guitar_acoustic_030-062-050_lower/ddsp.wav
                dwts: configs/resources/audio/guitar_acoustic_030-062-050_lower/dwts.wav
                nic: configs/resources/audio/guitar_acoustic_030-062-050_lower/nic.wav
          - type: mushra
            id: trial_string_lower
            name: MUSHRA Test
            content: This page shows a trial according to ITU-R Recommendation BS.1534. (String_Lower)
            enableLooping: true
            switchBack: true
            reference: configs/resources/audio/string_acoustic_056-064-100_lower/original.wav
            createAnchor35: false
            createAnchor70: true
            stimuli:
                ddsp: configs/resources/audio/string_acoustic_056-064-100_lower/ddsp.wav
                dwts: configs/resources/audio/string_acoustic_056-064-100_lower/dwts.wav
                nic: configs/resources/audio/string_acoustic_056-064-100_lower/nic.wav
          - type: mushra
          
            id: trial_vocal
            name: MUSHRA Test
            content: This page shows a trial according to ITU-R Recommendation BS.1534. (Vocal)
            enableLooping: true
            switchBack: true
            reference: configs/resources/audio/vocal_acoustic_000-066-127/original.wav
            createAnchor35: false
            createAnchor70: true
            stimuli:
                ddsp: configs/resources/audio/vocal_acoustic_000-066-127/ddsp.wav
                dwts: configs/resources/audio/vocal_acoustic_000-066-127/dwts.wav
                nic: configs/resources/audio/vocal_acoustic_000-066-127/nic.wav
    - 
          - random
          - type: likert_multi_stimulus
            id: trial_likert_ddsp
            name: Likert Scale
            content: Three random audio samples are included below. Rate each sample according to the effort required to identify which family they belong to.
            stimuli:
                guitar: configs/resources/audio/likert_ddsp/guitar_acoustic_015-051-025.wav
                mallet: configs/resources/audio/likert_ddsp/mallet_acoustic_062-078-100.wav
                string: configs/resources/audio/likert_ddsp/string_acoustic_057-071-025.wav
            response:
              - value: 5
                label: Complete relaxation; No effort required
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 4
                label: No appreciable effort required (Attention necessary)
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 3
                label: Moderate effort required
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 2
                label: Considerable effort required
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 1
                label: No meaning understood with any feasible effort
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png          
          - type: likert_multi_stimulus
            id: trial_likert_dwts
            name: Likert Scale
            content: Three random audio samples are included below. Rate each sample according to the effort required to identify which family they belong to.
            stimuli:
                guitar: configs/resources/audio/likert_dwts/guitar_acoustic_015-051-025.wav
                mallet: configs/resources/audio/likert_dwts/mallet_acoustic_062-078-100.wav
                string: configs/resources/audio/likert_dwts/string_acoustic_057-071-025.wav
            response:
              - value: 5
                label: Complete relaxation; No effort required
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 4
                label: No appreciable effort required (Attention necessary)
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 3
                label: Moderate effort required
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 2
                label: Considerable effort required
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 1
                label: No meaning understood with any feasible effort
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png          
          - type: likert_multi_stimulus
            id: trial_likert_nic
            name: Likert Scale
            content: Three random audio samples are included below. Rate each sample according to the effort required to identify which family they belong to.
            stimuli:
                guitar: configs/resources/audio/likert_nic/guitar_acoustic_015-051-025.wav
                mallet: configs/resources/audio/likert_nic/mallet_acoustic_062-078-100.wav
                string: configs/resources/audio/likert_nic/string_acoustic_057-071-025.wav
            response:
              - value: 5
                label: Complete relaxation; No effort required
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 4
                label: No appreciable effort required (Attention necessary)
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 3
                label: Moderate effort required
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 2
                label: Considerable effort required
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png
              - value: 1
                label: No meaning understood with any feasible effort
                img: configs/resources/images/star_off.png
                imgSelected: configs/resources/images/star_on.png
                imgHigherResponseSelected: configs/resources/images/star_on.png          
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
